# Generated by Django 4.1.3 on 2024-01-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(max_length=100)),
                ('priceProduct', models.IntegerField()),
                ('image', models.ImageField(upload_to='upload/menu/')),
                ('desc', models.CharField(max_length=100)),
                ('ukuran', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=2)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
    ]
